// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPiLZbtUMJCITMZiM3lMrJAcfSk6vFKwo',
    appId: '1:331243059076:web:56074dd24261fe4fe98fd1',
    messagingSenderId: '331243059076',
    projectId: 'khlasati',
    authDomain: 'khlasati.firebaseapp.com',
    storageBucket: 'khlasati.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC8e7lrvCP0fldoRrJbYuR4GLZ3TPmmIs',
    appId: '1:331243059076:android:535831315f5af68de98fd1',
    messagingSenderId: '331243059076',
    projectId: 'khlasati',
    storageBucket: 'khlasati.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtJV5WVI6o1Hr2WOw-gSOynJeNX2fCWGA',
    appId: '1:331243059076:ios:a4efc5a7f2518211e98fd1',
    messagingSenderId: '331243059076',
    projectId: 'khlasati',
    storageBucket: 'khlasati.firebasestorage.app',
    iosClientId: '331243059076-64lt2i12pvcrrkjuhcnuksr7pmh8lopt.apps.googleusercontent.com',
    iosBundleId: 'com.louaybarraq.paycheck',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtJV5WVI6o1Hr2WOw-gSOynJeNX2fCWGA',
    appId: '1:331243059076:ios:d8313fc394097d7ee98fd1',
    messagingSenderId: '331243059076',
    projectId: 'khlasati',
    storageBucket: 'khlasati.firebasestorage.app',
    iosBundleId: 'com.example.khlasati',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPiLZbtUMJCITMZiM3lMrJAcfSk6vFKwo',
    appId: '1:331243059076:web:aeb7a286faee141be98fd1',
    messagingSenderId: '331243059076',
    projectId: 'khlasati',
    authDomain: 'khlasati.firebaseapp.com',
    storageBucket: 'khlasati.firebasestorage.app',
  );
}
